; basing DGX Spark options from https://github.com/ggml-org/llama.cpp/blob/master/benches/dgx-spark/dgx-spark.md
; see `glow -p src/tools/server/README.md` for configuration options
[*]
flash-attn = on     ; defualt is auto (not needed?, or is this for misconfigured gguf?)
n-gpu-layers = -1   ; defualt is auto, changed for DGX Spark 
mmap = false        ; default is true, changed for DGX Spark

[gemma-4-12b-agentic-v2]
hf = yuxinlu1/gemma-4-12B-agentic-fable5-composer2.5-v2-3.5x-tau2-GGUF
hf-file = gemma4-v2-Q8_0.gguf  ; to keep it from picking up the wrong file
fit = false         ; google ai suggested this based on warnings, but the real issue was not related
; from the model card
ctx-size = 16384
temp = 1.0
top-p = 0.95
top-k = 64

[Qwythos-9B]
hf = empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF:Q8_0
; from the model card
temperature = 0.6
top-p = 0.95
top-k = 20
repeat-penalty = 1.05
predict = 16384
ctx-size = 32768
