; basing DGX Spark options from https://github.com/ggml-org/llama.cpp/blob/master/benches/dgx-spark/dgx-spark.md
; see `glow -p src/tools/server/README.md` for configuration options
[*]
flash-attn = on     ; defualt is auto (not needed?, or is this for misconfigured gguf?)
n-gpu-layers = -1   ; defualt is auto, changed for DGX Spark 
mmap = false        ; default is true, changed for DGX Spark
fit = false         ; https://tinyurl.com/bderaebv | forums.developer.nvidia.com/ help-on-llama-cpp-comma... /357012/2
; models-max = 2      ; the spark will crash with out of memory type behaviour
; parallel = 2
threads = 10        ; limit to 50% of the 20 CPUs
cache-ram = 0       ; https://tinyurl.com/722va4kj | forums.developer.nvidia.com glm 5.2 on 2x dgx spark ... /374523

; defaults for reference
; temperature = 0.8 
; top_p = 0.95
; repeat_penalty = 1.0 ; (1.0 = Disabled)
; dry_multiplier = 0.0 ; (0.0 = Disabled)

[Ornith-1.0-9B]
hf = protoLabsAI/Ornith-1.0-9B-MTP-GGUF:NVFP4
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4

[Ornith-1.0-35B-MXFP4_MOE] ; 70 t/p
hf = noctrex/Ornith-1.0-35B-MXFP4_MOE-GGUF:MXFP4_MOE
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4

[Qwen3.6-27B-Q2_K_XL]  ; 26 t/s
hf = unsloth/Qwen3.6-27B-MTP-GGUF:Q2_K_XL
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
; ctx-size = 16384
; spec-draft-ngl = 99
; repeat-penalty = 1.05
temp = 1.0

[Qwen3.6-27B-NVFP4-GGUF]  ; 20 t/s
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
ctx-size = 16384
; spec-draft-ngl = 99

[gemma-4-12b-agentic-fabel5-composer2.5-v2:Q8_0] ; 17 t/s
hf = yuxinlu1/gemma-4-12B-agentic-fable5-composer2.5-v2-3.5x-tau2-GGUF
hf-file = gemma4-v2-Q8_0.gguf  ; to keep it from picking up the wrong file
; from the model card
ctx-size = 16384
temp = 1.0
top-p = 0.95
top-k = 64

[Qwythos-9B-Q8_0]  ; 25.6 t/s
hf = empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF:Q8_0
; from the model card
temperature = 0.6
top-p = 0.95
top-k = 20
repeat-penalty = 1.05
;predict = 16384
;ctx-size = 32768

[Qwen3.6-35B-A3B-MXFP4_MOE] ; 67.8 t/s
hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:MXFP4_MOE
; https://forums.developer.nvidia.com/t/mtp-llama-cpp-a-look-at-qwen3-6-27b/370298
ctx-size = 262144
;spec-type = draft-mtp
;spec-draft-n-max = 4
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
spec-draft-ngl = 99
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.05
repeat-penalty = 1.05
presence-penalty = 0.00
; --chat-template-kwargs '{"preserve_thinking": true}'
;spec-draft-n-max = 5
;spec-draft-p-min = 0.75

[gemma-4-26B-A4B-MXFP4_MOE] ; 84.4
hf = unsloth/gemma-4-26B-A4B-it-GGUF:MXFP4_MOE
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
spec-draft-ngl = 99
